Update strings.po
CastagnaIT/plugin.video.netflix pull request #1181
Opened 2021-06-03 21:41 UTC by djdirty60

Updated

### Check if this PR fulfills these requirements:
* [ ] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [ ] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [ ] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [ ] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

### In case of Feature change / Breaking change:
#### Describe the current behavior

#### Describe the new behavior

### Screenshots (if appropriate):

2021-06-06 09:35 UTC, CastagnaIT requested changes
Currently this translation is maintained by @michaelarnauts,
but i see has not been updated for some time
if the previous maintainer have no intention of continuing to keep it up to date, i might suggest a change of maintainer, if you wish of course

changes will be accepted upon confirmation of @michaelarnauts, If no reply will be received, they will be accepted as they are.

There are some things to be fixed:
- When you create a PR please write an appropriate Title
- Addon checker check has failed see check error details
- Some ID's are not filled, please add missing translations

2021-06-06 17:31 UTC, michaelarnauts commented on resources/language/resource.language.nl_nl/strings.po
> +msgstr "Forceer de weergave van geforceerde ondertitels alleen met de audiotaal ingesteld""
Duplicate end quote

2021-06-06 17:33 UTC, michaelarnauts commented on resources/language/resource.language.nl_nl/strings.po
> +msgstr "ID bekijken voor shows"
"ID voor shows bekijken" so it is consistent?

2021-06-06 17:34 UTC, michaelarnauts commented on resources/language/resource.language.nl_nl/strings.po
> +msgstr "Profiel opties en ouderlijk toezicht"
Profielopties should be one word

2021-06-17 06:43 UTC, CastagnaIT commented
If no reply is given within 3 days, this PR will be closed

2021-06-20 08:12 UTC, closed without merging