Update strings.po
CastagnaIT/plugin.video.netflix pull request #1275
Opened 2021-12-06 00:31 UTC by djdirty60

Updated

### Check if this PR fulfills these requirements:
* [ ] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [ ] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [ ] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [ ] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which changes behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactor (non-breaking performance or readability improvements)

### Description

### In case of Feature change / Breaking change:
#### Describe the current behavior

#### Describe the new behavior

### Screenshots (if appropriate):

2021-12-06 00:32 UTC, djdirty60 commented
Updated

2021-12-11 17:28 UTC, CastagnaIT requested changes

2021-12-11 17:28 UTC, CastagnaIT commented on resources/language/resource.language.nl_nl/strings.po
> +msgstr "[B]Indien uitgeschakeld, veroorzaakt dit een beveiligingslek[/B].  Als uw besturingssysteem dit niet ondersteunt, wordt u elke keer dat u het apparaat opnieuw opstart gevraagd om in te loggen
something wrong with `[B][/B]` contains no words

2021-12-11 17:32 UTC, CastagnaIT commented
`Translations / Check translations (matrix) (pull_request)` is failed

resources/language/resource.language.nl_nl/strings.po:156: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:160: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:164: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:168: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:172: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:176: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:180: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:184: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:262: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:330: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:614: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:618: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:622: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:638: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:1046: this message is untranslated
resources/language/resource.language.nl_nl/strings.po:1062: this message is untranslated

2022-01-28 19:08 UTC, CastagnaIT commented
if request changes will be not addressed in few days this PR will be closed

2022-02-05 07:51 UTC, closed without merging